### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by movh** [PCJones/UmlautAdaptarr#52]
Are there any plans of implementing ARM architecture support?

**Comment by PCJones** [comment]
Do you want a docker image or are you fine with a build?

**Comment by movh** [comment]
Docker Compose would be awesome,  if there are others interested.

**Comment by PCJones** [comment]
I don't have an ARM device to test on at the moment, could you try this docker compose?

```
services:
  umlautadaptarr:
    # Uncomment this to get the development branch
    # build:
    #   context: https://github.com/PCJones/UmlautAdaptarr.git#develop
    build:
      context: https://github.com/PCJones/UmlautAdaptarr.git#master
      dockerfile: Dockerfile.arm64
    image: umlautadaptarr
    restart: unless-stopped
    ports:
      - "5005:5005" # can be removed if you use the recommended prowlarr+proxy configuration
      - "5006:5006" # can be removed if you use the alternative, non-proxy configuration
    environment:
      # as usual
```
