### ISSUE TITLE
Configuration Error in Portainer

### ISSUE THREAD

**Issue by Pattern91** [PCJones/UmlautAdaptarr#63]
Hi @PCJones ,

thanks for your work. This my current configuration in the Portainer stack

```
version: '3.8'
services:
  umlautadaptarr:
    #uncomment this to get the development branch
    #build: https://github.com/PCJones/UmlautAdaptarr.git#develop
    build: https://github.com/PCJones/UmlautAdaptarr.git#master
    image: umlautadaptarr
    restart: unless-stopped
    ports:
      - 5006:5006 # can be removed if you use the alternative, non-proxy configuration
    environment:
      - TZ=Europe/Berlin
      - RADARR__ENABLED=true
      - RADARR__HOST=http://10.x.x.x:7878
      - RADARR__APIKEY='3fxxxxxxxxxxxxx0'
``` 

But I get Error:
`Error while registering ArrFactory. This is most likely a config problem, please check your environment variables.`

I already tried using "5006:5006" so with " " and also for the API Key I tried it with ' ' and without. Can you help me spot the error?

**Comment by Mr72PS** [comment]
Hi

my stack code in portainer is as follows and it worked to install on my synology:

version: '3.8'
services:
  umlautadaptarr:
    image: pcjones/umlautadaptarr:latest
    container_name: umlautadaptarr
    environment:
      - PUID=1020  # Replace with your Synology user ID
      - PGID=100   # Replace with your Synology group ID
      - TZ=Europe/Berlin  # Replace with your timezone
      - RADARR__ENABLED=true
      - RADARR__HOST=http://xxx.xxx.x.xxx:7878  # Replace with your Radarr URL
      - RADARR__APIKEY=3xxxxxxxxxxxxxxxxxxxxxx  # Replace with your Radarr API key
    volumes:
      - /volume1/docker/umlautadaptarr/config:/config  # Replace with your desired config path
    ports:
      - "5005:5005" # can be removed if you use the recommended prowlarr+proxy configuration 
      - "5006:5006" # can be removed if you use the alternative, non-proxy configuration
    restart: unless-stopped

**Comment by Pattern91** [comment]
I updated it now to this, but I still get the same error:


```
umlautadaptarr:
    image: pcjones/umlautadaptarr:latest
    container_name: umlautadaptarr
    environment:
      - PUID=1000  # Replace with your Synology user ID
      - PGID=10000   # Replace with your Synology group ID
      - TZ=Europe/Berlin  # Replace with your timezone
      - RADARR__ENABLED=true
      - RADARR__HOST=http://10.0.0.5:7878  # Replace with your Radarr URL
      - RADARR__APIKEY=3f2561de80c54d89a5575afcdbd31ea0  # Replace with your Radarr API key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/umlautadaptarr:/config  # Replace with your desired config path
    ports:

      - "5006:5006" # can be removed if you use the alternative, non-proxy configuration
    restart: unless-stopped
```
